//! CHARMM structure file (`.psf`) rendering of a particle list.
//!
//! The PSF records the system's atoms (with charge, mass and type) and its
//! bonded connectivity. Lipid chains are linear, so bonds and
//! angles are read directly off each molecule's consecutive beads; dihedral,
//! improper, donor and acceptor sections are empty. A [`Membrane`] renders
//! through the [`render`] core.

use std::fmt::Write;

use crate::membrane::{Membrane, Particle, molecule_ranges};

/// Segment name used for every molecule.
const SEGMENT: &str = "MEMB";

/// Render a particle list as a CHARMM `.psf` structure file.
pub fn render(particles: &[Particle], name: &str) -> String {
    let molecules = molecule_ranges(particles);

    // Bonds connect consecutive beads in each molecule; angles span triples.
    let mut bonds = Vec::new();
    let mut angles = Vec::new();
    for range in &molecules {
        let chain = &particles[range.clone()];
        for pair in chain.windows(2) {
            bonds.extend([pair[0].atom_id, pair[1].atom_id]);
        }
        for triple in chain.windows(3) {
            angles.extend([triple[0].atom_id, triple[1].atom_id, triple[2].atom_id]);
        }
    }

    let mut s = String::new();
    let _ = writeln!(s, "PSF\n");
    let _ = writeln!(s, "{:>8} !NTITLE", 1);
    let _ = writeln!(s, " REMARKS {name} generated by isolf\n");

    let _ = writeln!(s, "{:>8} !NATOM", particles.len());
    for particle in particles {
        write_atom(&mut s, particle);
    }
    let _ = writeln!(s);

    // Bonds: 4 per line (8 indices); angles: 3 per line (9 indices).
    let _ = writeln!(s, "{:>8} !NBOND: bonds", bonds.len() / 2);
    write_indices(&mut s, &bonds, 8);
    let _ = writeln!(s);

    let _ = writeln!(s, "{:>8} !NTHETA: angles", angles.len() / 3);
    write_indices(&mut s, &angles, 9);
    let _ = writeln!(s);

    for label in [
        "!NPHI: dihedrals",
        "!NIMPHI: impropers",
        "!NDON: donors",
        "!NACC: acceptors",
    ] {
        let _ = writeln!(s, "{:>8} {label}\n", 0);
    }

    // Non-bonded exclusion list: none, but the per-atom pointer array (all zeros)
    // is still required.
    let _ = writeln!(s, "{:>8} !NNB", 0);
    write_indices(&mut s, &vec![0; particles.len()], 8);
    let _ = writeln!(s);

    // A single group spanning the whole system.
    let _ = writeln!(s, "{:>8} {:>8} !NGRP", 1, 0);
    let _ = writeln!(s, "{:>8} {:>8} {:>8}", 0, 0, 0);
    let _ = writeln!(s);
    s
}

impl Membrane {
    /// Render this membrane as a CHARMM `.psf` structure file.
    pub fn to_psf(&self) -> String {
        render(&self.particles, &self.name)
    }
}

fn write_atom(s: &mut String, particle: &Particle) {
    let _ = writeln!(
        s,
        "{:>8} {:<4} {:<4} {:<4} {:<4} {:<4} {:>10.6} {:>13.6} {:>11}",
        particle.atom_id,
        SEGMENT,
        particle.molecule_id,
        particle.residue,
        particle.bead,
        particle.bead,
        particle.charge,
        particle.mass,
        0,
    );
}

/// Write a flat list of atom indices, `per_line` to a line, in 8-wide columns.
fn write_indices(s: &mut String, values: &[usize], per_line: usize) {
    for chunk in values.chunks(per_line) {
        for value in chunk {
            let _ = write!(s, "{value:>8}");
        }
        let _ = writeln!(s);
    }
}

#[cfg(test)]
mod tests {
    use crate::composition::Composition;
    use crate::force_field::ForceField;
    use crate::membrane::{BuildOptions, DEFAULT_NAME, Membrane, Sizing};
    use rand::SeedableRng;
    use rand::rngs::StdRng;

    fn membrane() -> Membrane {
        let force_field = ForceField::isolf();
        let leaflet = Composition::parse("DLPC=1").unwrap();
        let mut rng = StdRng::seed_from_u64(1);
        Membrane::build(
            &force_field,
            DEFAULT_NAME,
            &leaflet,
            &leaflet,
            Sizing::Count { upper: 4, lower: 4 },
            &BuildOptions::default(),
            &mut rng,
        )
        .unwrap()
    }

    #[test]
    fn header_and_counts_are_consistent() {
        let membrane = membrane();
        let psf = membrane.to_psf();

        assert!(psf.starts_with("PSF\n"));
        // 8 DLPC lipids × 5 beads = 40 atoms.
        assert!(psf.contains("      40 !NATOM"));
        // Each 5-bead chain has 4 bonds and 3 angles, over 8 chains.
        assert!(psf.contains(&format!("{:>8} !NBOND: bonds", 8 * 4)));
        assert!(psf.contains(&format!("{:>8} !NTHETA: angles", 8 * 3)));
        assert!(psf.contains("       0 !NPHI: dihedrals"));
    }

    #[test]
    fn atom_lines_carry_charge_and_mass() {
        let membrane = membrane();
        let psf = membrane.to_psf();
        // The phosphate bead PHO carries a -1 charge and ~109 g/mol mass.
        let pho_line = psf
            .lines()
            .find(|l| l.contains(" PHO ") && l.contains("MEMB"))
            .expect("a PHO atom line");
        assert!(pho_line.contains("-1.000000"));
        assert!(pho_line.contains("108.998600"));
    }
}
